site_name: phylojs
site_url: https://clockor2.github.io/phylojs/
repo_url: https://github.com/clockor2/phylojs
edit_uri: https://github.com/clockor2/phylojs/edit/main/docs/

theme:
  name: "material"
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: images/logo.png
  favicon: images/logo-pink.png
  features:
    - toc.follow
    - content.action.edit
    - content.code.copy
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - content.action.edit
    - content.action.view
    - navigation.tracking
    - navigation.tabs
    - navigation.expand

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list

plugins:
  - search
  - mkdocs-video:
      is_video: True
      video_muted: True
      video_controls: True
      css_style:
        width: "100%"
  - typedoc:
      source: "./src/"
      tsconfig: "tsconfig.json"
      name: "API"
      options: "typedoc.json"
      disable_system_check: False

nav:
  - Home:
      - "index.md"
      - Overview of the Tree Class: examples/tree.md
      - Writing Trees: examples/writer.md

  - Examples:
      - examples/index.md
      - Random-Rerooting App: examples/rerootingApp.md
      - Ladderising App: examples/ladderiseApp.md
      - Newick Conversion App: examples/toNewickApp.md
      - Tree Statistics App: examples/treeStatsApp.md
      - Annotations and Pre-Order Traversal: examples/annotationsPreOrder.md
      - Fetching Trees from a URL: examples/fetch.md
      - Root-to-tip regression: examples/rttr.md
      - Pruning and Grafting: examples/pruneGraft.md
      - Extracting Clades: examples/mrca.md
      - Modifying Annotations: examples/annotations.md
      - Arrays of Trees: examples/treeArray.md
  - API: "typedoc"
  - Cite: cite.md
