
site_name: phylojs
site_url: https://clockor2.github.io/phylojs/
repo_url: https://github.com/clockor2/phylojs

theme:
  name: "material"
  palette: 
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: images/logo.png
  favicon: images/logo-pink.png
  features:
    - toc.follow
    - content.action.edit
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - content.action.edit
    - content.action.view
    - navigation.tracking
    - navigation.tabs
    - navigation.expand

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
- search
- mkdocs-video:
    is_video: True
    video_muted: True
    video_controls: True
    css_style:
      width: "100%"
- typedoc:
    source: './src/'
    tsconfig: 'tsconfig.json'
    name: 'API'
    options: 'typedoc.json'
    disable_system_check: False

nav:
  - Home: 'index.md'
  - Examples:
    - examples/index.md
    - Overview of the Tree Class: examples/tree.md
    - Visualise: examples/visualise.md
    - Finding the MRCA: examples/mrca.md
    - Root-to-tip regression: examples/rttr.md
    - Rerooting: examples/reroot.md
    - Working with annotations: examples/annotations.md
    - Working with arrays of trees: examples/treeArray.md
    - Writing trees: examples/writer.md
  - API: 'typedoc'
  - Cite: cite.md